### PR TITLE
 Add Webserver Config Page

### PR DESCRIPTION
**Pull request by Mevel**
Super Simple Config Page loaded from Config file.
Upload new WAV Files via web UI.
Edit all Config parameters and save.

had to change the default interface to local 127.0.0.1 as a bind on 0.0.0.0 did not work somehow.

updated requirements as it is using ruamel.yaml to keep the original yaml file including comments

config-edit

### CODE REVIEW

**Comment by Mevel** [comment]
i added a shutdown button aswell to safely shutdown the Pi and not rist data corruption

**Comment by nickpourazima** [comment]
Super awesome, thanks again for all your work! I'll test it out this weekend and drop an updated .iso release if all goes well

**Comment by Mevel** [comment]
I added boostrap layout 
audio player
single download
zip download


grafik

and card layout to the config page

grafik

**Comment by Mevel** [comment]
please check on your setup before i break anything ^^

**Review by nickpourazima — APPROVED** [review]
Thanks @Mevel, looks great! I might add a few more visualization tweaks pretty soon in a separate commit.

**Pull request merged**
